package net.careerboard.models.dto;

public enum ResDTOMessage {
    USERNAME_ALREADY_EXIST, CREATED, FAILED, NOT_FOUND, ALREADY_VERIFIED,  INVALID_CREDENTIALS,
    
     SUCCESS, UNEXPECTED_ERROR, WRONG_PASSWORD, WRONG_CREDENTIALS, 

    INTERNAL_SERVER_ERROR,  INVALID_ACCESS_TOKEN, VALIDATION_ERROR,DATABASE_CONSTRAINT_VIOLATION,
    WRONG_USERNAME_OR_PASSWORD, 

     UNAUTHORIZED, INVALID_MESSAGE_CONTENT, UNSUPPORTED
}
