spring:
  application:
    name: career-board
  datasource:
    url: ${POSTGRES_URL} # Update to point to your local PostgreSQL
    username: ${POSTGRES_USER} # Replace with your local PostgreSQL username
    password: ${POSTGRES_PASSWORD} # Replace with your local PostgreSQL password
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties: { } # Remove Google Cloud SQL socket factory properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${POSTGRES_DEFAULT_SCHEMA}
    hibernate:
      ddl-auto: none

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

greeting: "${sm://projects/553556926651/secrets/greeting/versions/1}"

server:
  port: 8081

aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
    presign-duration-minutes: 30


cors:
  allowed-origins:
    - "localhost:8081"
    - "http://localhost:4200"
    - "https://chitshit.online"
