spring:
  application:
    name: career-board
  datasource:
    url: jdbc:mysql://localhost:3306/career-board
    username: root
    password: oracle
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties: {}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Recommended for MySQL 8+
    hibernate:
      ddl-auto: update  # This will automatically create/update tables
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  flyway:
    enabled: false  # Disable Flyway if not needed

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

greeting: "${sm://projects/553556926651/secrets/greeting/versions/1}"

server:
  port: 8081

aws:
  access-key: ${AWS_ACCESS_KEY_ID:dummyAccessKey}      # Default if not set
  secret-key: ${AWS_SECRET_ACCESS_KEY:dummySecretKey}    # Default if not set
  region: ${AWS_REGION:us-east-1}                        # Default region
  s3:
    bucket-name: ${AWS_BUCKET_NAME:dummyBucketName}      # Default bucket name
    presign-duration-minutes: 30

production:
  domain: ${PRODUCTION_DOMAIN:localhost}  # Defaults to localhost if not set
environment: ${ENVIRONMENT:dev}            # Defaults to dev if not set
